apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: tenshi-portal
  namespace: tenshi-portal
  labels:
    release: monitoring
    app.kubernetes.io/name: tenshi-portal
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: tenshi-portal
  namespaceSelector:
    matchNames:
      - tenshi-portal
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
