apiVersion: v1
kind: Service
metadata:
  name: tenshi-portal-app
  namespace: tenshi-portal
  labels:
    app.kubernetes.io/name: tenshi-portal-app
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: tenshi-portal
  ports:
    - name: http
      port: 8080
      targetPort: http
